version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "maintenance"
      - "dependencies"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "build(deps):"
    groups:
      dependencies:
          patterns:
            - "*"

      doc-deps:
          patterns:
            - "ansys-sphinx-theme*"
            - "sphinx*"
            - "nbsphinx"
            - "jupyter_sphinx"
            - "numpydoc"
            - "autodoc_pydantic"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "maintenance"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "ci"
    groups:
       actions:
          patterns:
            - "*"
